name: Endpoint Test

on:
  push:
    branches: [ master ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3 
        - name: Enter in repo dir
          run: cd /home/runner/work/Bookfinder-Kotlin/Bookfinder-Kotlin
        - name: Test Gradle Build
          run: ls && chmod +x gradlew && ./gradlew :test --tests "it.tn.spoilers.ApplicationTest"
