name: Endpoint Test

on:
  push:
    branches: [ master ]

test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3 
        - name: Test Gradle Build
          run: chmod +x ./gradlew && ./gradlew :test --tests "it.tn.spoilers.ApplicationTest"
